### ISSUE TITLE
error Unexpected token in JSON at position 3384 (Position change depending on state paradigm is in)

### ISSUE THREAD

**Issue by retepsmada** [bitfocus/companion-module-etc-paradigm#9]
Whenever I try to connect to my Paradigm controller I get a different unexpected token in the JSON every time depending on the state that parardigm is currently in. I've attached the log and some screenshots of what I'm seeing as well, running companion on a Macbook Air 2015 running MacOS Monteray. Companion Version 3.1.2. Paradigm version 3.1.2 as well, ERn rack.
![Screenshot 2024-01-03 at 20 39 26](https://github.com/bitfocus/companion-module-etc-paradigm/assets/13811671/d60eda29-cea4-4e96-95ef-42dce6cec0e3)
![Screenshot 2024-01-03 at 20 39 39](https://github.com/bitfocus/companion-module-etc-paradigm/assets/13811671/6cdc84b9-6579-4c2c-a2f9-05f643befe90)
![Screenshot 2024-01-03 at 20 43 47](https://github.com/bitfocus/companion-module-etc-paradigm/assets/13811671/50298b41-51de-4bad-8bff-3b52ec34e776)
[module-log-03_01_2024-20 36 24.csv](https://github.com/bitfocus/companion-module-etc-paradigm/files/13823199/module-log-03_01_2024-20.36.24.csv)

**Comment by zerbzman** [comment]
Ok would you be able to go to this address [http://10.101.10.101/get/system](http://10.101.10.101/get/system) and paste the contents here? It looks like there is something that it is not expecting. Thanks

**Comment by zerbzman** [comment]
You mention a certain "state". Is this when you have a specific preset or macro launched? The paradigm might not be sending back totally correct data when this happens and causing this to throw an error. Would you be able to go to this address as well and paste the result? http://10.101.10.101/get/system/control_status

**Comment by retepsmada** [comment]
{"processor_name":"Processor 1","processor_number":1,"ip_address":174393957,"current_time":"04/01/2024 2:31pm (UTC+0)","uptime":5465173,"rack_status":"ERn","stations":[{"number":"1","name":"DSR","status":"Online"},{"number":"2","name":"Control Room","status":"Online"},{"number":"4","name":"16in Contact Stn 1","status":"Online"}],"mosaics":[],}
![Screenshot 2024-01-04 at 14 35 19](https://github.com/bitfocus/companion-module-etc-paradigm/assets/13811671/cfb1b2e5-e457-43e1-95ba-e443474545ab)

The second link just leads to a blank page served by the webserver

**Comment by zerbzman** [comment]
Thanks!

Whoops, my bad. The second link should be this. http://10.101.10.101/get/control_status

**Comment by retepsmada** [comment]
{"presets":{7:"Activated",8:"Deactivated",9:"Deactivated",10:"Deactivated",11:"Activated",12:"Deactivated",13:"Deactivated",14:"Deactivated",15:"Deactivated",16:"Deactivated",17:"Deactivated",18:"Deactivated",19:"Deactivated",20:"Deactivated",21:"Deactivated",22:"Deactivated",23:"Deactivated",26:"Deactivated",27:"Deactivated"},"sequences":{},"walls":{},"channels":{0:0,1:0,2:0,3:0,4:0,5:0,6:0,7:0,8:0,9:0,10:0,11:0,12:0,13:0,14:0,15:0,16:71,17:71,18:71,19:71,20:71,21:71,22:71,23:71,24:95,28:0,52:0,53:0,60:67,61:67,62:67,63:67,64:67,65:67,66:67,67:67,68:67,69:68,70:68,71:68,72:68,73:68,74:68,75:68,76:68,77:68,78:73,79:73,84:95,85:95,86:95,87:95,88:95,91:73,92:73,93:73,94:73,95:74,110:74,111:74,112:74,113:74,114:74,115:0,116:0,117:0,118:0,119:0,120:0,121:0,122:0,123:0,124:0,125:0,126:0,127:0,128:0,130:74,131:74,132:71,134:96,135:100,136:100,137:100,138:100,139:100,140:100,141:100,142:100,143:100,144:100,145:100,146:100,147:100,148:100,149:100,150:100,151:100,153:100,154:100,155:100,156:100,157:100,158:100,159:100,169:73,170:73,171:73,172:71,173:71,174:71,175:71,176:71,177:71,178:71,179:71,180:71,181:74,182:0,206:0,207:0,208:0,209:0,210:0,211:0,212:0,213:0,214:0,215:0,216:0,217:0,218:0,219:0,220:0,221:0,222:0,223:0,224:0,225:0,226:0,227:0,228:0,229:0,230:0,231:0,232:0,233:0,234:0,235:0,236:0,237:0,238:0,239:0,240:0,241:0,242:0,243:0,244:0,245:0,246:0,247:0,248:0,249:0,250:0,251:0,252:0,253:0,254:0,255:0,256:0,257:0,258:0,259:0,260:0,261:0,262:0,263:0,264:0,265:0,266:0,267:0,268:0,269:0,270:0,271:0,272:0,273:0,274:0,275:0,276:0,277:0,278:0},"macros":{0:1,1:0,2:0,3:0,4:0,5:0,6:0,10:0,11:0,12:0,13:0},"overrides":{0:true,1:true}}

**Comment by zerbzman** [comment]
Thanks! That all looks correct.

After looking at the logs again it looks like the issue is in the starting connection. This plugin makes several calls to the Paradigm to get info for presets, macros, channels, walls, and overrides as well as a call for general system info. My guess based on the position of the error being 3384, is that there may be an issue with a channel name. To know for sure and be able to fix it, would you be able to go through each of these links and paste the result again?

1. http://10.101.10.101/get/spaces
2. http://10.101.10.101/get/overrides
3. http://10.101.10.101/get/walls
4. http://10.101.10.101/get/channels
5. http://10.101.10.101/get/sequences
6. http://10.101.10.101/get/presets
7. http://10.101.10.101/get/macros

Thanks!

**Comment by retepsmada** [comment]
1.
{"0":"Global","1":"House Lights","2":"Work Lights","3":"Independants","4":"Bridge 1","6":"Bridge 2","7":"Bridge 3","8":"Bridge 4","9":"Bridge 5","10":"Bridge 6","5":"Exit Signs","11":"Lobbies","12":"Unused Channels","13":"Space 7","14":"Space 8","15":"Dimmer Ccts"}
2. 
[{"id":0,"name":"Cleaners Lock","state":true},{"id":1,"name":"PIT LED STATUS","state":true}]
3. 

4. 
[{"id":0,"name":"IND 1","space":3,"level":0},{"id":1,"name":"IND 2","space":3,"level":0},{"id":2,"name":"IND 3","space":3,"level":0},{"id":3,"name":"IND 4","space":3,"level":0},{"id":4,"name":"IND 5","space":3,"level":0},{"id":5,"name":"IND 6","space":3,"level":0},{"id":6,"name":"IND 7","space":3,"level":0},{"id":7,"name":"IND 8","space":3,"level":0},{"id":8,"name":"IND 9","space":3,"level":0},{"id":9,"name":"IND 10","space":3,"level":0},{"id":10,"name":"IND 11","space":3,"level":0},{"id":11,"name":"IND 12","space":3,"level":0},{"id":12,"name":"IND 13","space":3,"level":0},{"id":13,"name":"IND 14","space":3,"level":0},{"id":14,"name":"IND 15","space":3,"level":0},{"id":15,"name":"IND 16","space":3,"level":0},{"id":16,"name":"HL-1","space":4,"level":71},{"id":17,"name":"HL-2","space":4,"level":71},{"id":18,"name":"HL-3","space":4,"level":71},{"id":19,"name":"HL-4","space":4,"level":71},{"id":20,"name":"HL-5","space":4,"level":71},{"id":21,"name":"HL-6","space":4,"level":71},{"id":22,"name":"HL-7","space":4,"level":71},{"id":23,"name":"HL-8","space":4,"level":71},{"id":24,"name":"Exit Signs Stage ChB","space":5,"level":95},{"id":28,"name":"Cloth Store","space":2,"level":0},{"id":52,"name":"Dimmer 1","space":1,"level":0},{"id":53,"name":"Dimmer 2","space":1,"level":0},{"id":60,"name":"HL-10","space":6,"level":67},{"id":61,"name":"HL-11","space":6,"level":67},{"id":62,"name":"HL-12","space":6,"level":67},{"id":63,"name":"HL-13","space":6,"level":67},{"id":64,"name":"HL-14","space":6,"level":67},{"id":65,"name":"HL-15","space":6,"level":67},{"id":66,"name":"HL-16","space":6,"level":67},{"id":67,"name":"HL-17","space":6,"level":67},{"id":68,"name":"HL-18","space":6,"level":67},{"id":69,"name":"HL-19","space":7,"level":68},{"id":70,"name":"HL-20","space":7,"level":68},{"id":71,"name":"HL-21","space":7,"level":68},{"id":72,"name":"HL-22","space":7,"level":68},{"id":73,"name":"HL-23","space":7,"level":68},{"id":74,"name":"HL-24","space":7,"level":68},{"id":75,"name":"HL-25","space":7,"level":68},{"id":76,"name":"HL-26","space":7,"level":68},{"id":77,"name":"HL-27","space":7,"level":68},{"id":78,"name":"HL-28","space":8,"level":73},{"id":79,"name":"HL-29","space":8,"level":73},{"id":84,"name":"Exit Signs Strage Left ChA","space":5,"level":95},{"id":85,"name":"Exit Signs Strage Left ChB","space":5,"level":95},{"id":86,"name":"Exit Signs Stage ChA","space":5,"level":95},{"id":87,"name":"Exit Signs Strage Right ChA","space":5,"level":95},{"id":88,"name":"Exit Signs Strage Right ChB","space":5,"level":95},{"id":91,"name":"HL-30","space":8,"level":73},{"id":92,"name":"HL-31","space":8,"level":73},{"id":93,"name":"HL-32","space":8,"level":73},{"id":94,"name":"HL-33","space":8,"level":73},{"id":95,"name":"HL-47","space":10,"level":74},{"id":110,"name":"HL-48","space":10,"level":74},{"id":111,"name":"HL-49","space":10,"level":74},{"id":112,"name":"HL-50","space":10,"level":74},{"id":113,"name":"HL-51","space":10,"level":74},{"id":114,"name":"HL-52","space":10,"level":74},{"id":115,"name":"Blue 1 - Bridge 0 & 1","space":2,"level":0},{"id":116,"name":"Blue 2 - Bridge 2 & 3","space":2,"level":0},{"id":117,"name":"Blue 3 - Bridge 4 & 5","space":2,"level":0},{"id":118,"name":"Blue 4 - Bridge 6","space":2,"level":0},{"id":119,"name":"Blue 5 - Catwalks","space":2,"level":0},{"id":120,"name":"Blue 6","space":2,"level":0},{"id":121,"name":"TRIMMING\
GALLEERY","space":2,"level":0},{"id":122,"name":"FLYS\
SR","space":2,"level":0},{"id":123,"name":"HEMP\
GALLERY","space":2,"level":0},{"id":124,"name":"WINGS","space":2,"level":0},{"id":125,"name":"UP\
STAGE","space":2,"level":0},{"id":126,"name":"CATWALK\
LOBBIES","space":2,"level":0},{"id":127,"name":"SUB\
STAGE","space":2,"level":0},{"id":128,"name":"ORCHESTRA\
PIT","space":2,"level":0},{"id":130,"name":"HL-53","space":10,"level":74},{"id":131,"name":"HL-54","space":10,"level":74},{"id":132,"name":"HL-9","space":4,"level":71},{"id":134,"name":"Lobbies","space":11,"level":96},{"id":135,"name":"WL-01","space":2,"level":100},{"id":136,"name":"WL-02","space":2,"level":100},{"id":137,"name":"WL-03","space":2,"level":100},{"id":138,"name":"WL-04","space":2,"level":100},{"id":139,"name":"WL-05","space":2,"level":100},{"id":140,"name":"WL-06","space":2,"level":100},{"id":141,"name":"WL-07","space":2,"level":100},{"id":142,"name":"WL-08","space":2,"level":100},{"id":143,"name":"WL-09","space":2,"level":100},{"id":144,"name":"WL-10","space":2,"level":100},{"id":145,"name":"WL-11","space":2,"level":100},{"id":146,"name":"WL-12","space":2,"level":100},{"id":147,"name":"WL-13","space":2,"level":100},{"id":148,"name":"WL-14","space":2,"level":100},{"id":149,"name":"WL-15","space":2,"level":100},{"id":150,"name":"WL-16","space":2,"level":100},{"id":151,"name":"FoH\
CATWALKS","space":2,"level":100},{"id":153,"name":"GRID","space":2,"level":100},{"id":154,"name":"STAGE\
FLOODS","space":2,"level":100},{"id":155,"name":"FLYS & \
HEMP","space":2,"level":100},{"id":156,"name":"WINGS","space":2,"level":100},{"id":157,"name":"UP\
STAGE","space":2,"level":100},{"id":158,"name":"ORCHESTRA\
PIT","space":2,"level":100},{"id":159,"name":"SUB\
STAGE","space":2,"level":100},{"id":169,"name":"HL-34","space":8,"level":73},{"id":170,"name":"HL-35","space":8,"level":73},{"id":171,"name":"HL-36","space":8,"level":73},{"id":172,"name":"HL-37","space":9,"level":71},{"id":173,"name":"HL-38","space":9,"level":71},{"id":174,"name":"HL-39","space":9,"level":71},{"id":175,"name":"HL-40","space":9,"level":71},{"id":176,"name":"HL-41","space":9,"level":71},{"id":177,"name":"HL-42","space":9,"level":71},{"id":178,"name":"HL-43","space":9,"level":71},{"id":179,"name":"HL-44","space":9,"level":71},{"id":180,"name":"HL-45","space":9,"level":71},{"id":181,"name":"HL-46","space":10,"level":74},{"id":182,"name":"Music Stands (5amp ccts)","space":2,"level":0},{"id":206,"name":"Dimmer 3","space":1,"level":0},{"id":207,"name":"Dimmer 4","space":1,"level":0},{"id":208,"name":"Dimmer 5","space":1,"level":0},{"id":209,"name":"Dimmer 6","space":1,"level":0},{"id":210,"name":"Dimmer 7","space":1,"level":0},{"id":211,"name":"Dimmer 8","space":1,"level":0},{"id":212,"name":"Dimmer 9","space":1,"level":0},{"id":213,"name":"Dimmer 10","space":1,"level":0},{"id":214,"name":"Dimmer 11","space":1,"level":0},{"id":215,"name":"Dimmer 12","space":1,"level":0},{"id":216,"name":"Dimmer x184","space":1,"level":0},{"id":217,"name":"Dimmer x210","space":1,"level":0},{"id":218,"name":"Dimmer x209","space":1,"level":0},{"id":219,"name":"Dimmer x208","space":1,"level":0},{"id":220,"name":"Dimmer x207","space":1,"level":0},{"id":221,"name":"Dimmer x206","space":1,"level":0},{"id":222,"name":"Dimmer x205","space":1,"level":0},{"id":223,"name":"Dimmer x204","space":1,"level":0},{"id":224,"name":"Dimmer x203","space":1,"level":0},{"id":225,"name":"Dimmer x202","space":1,"level":0},{"id":226,"name":"Dimmer x201","space":1,"level":0},{"id":227,"name":"Dimmer x200","space":1,"level":0},{"id":228,"name":"Dimmer x199","space":1,"level":0},{"id":229,"name":"Dimmer 114","space":1,"level":0},{"id":230,"name":"Dimmer 85","space":1,"level":0},{"id":231,"name":"Dimmer x183","space":1,"level":0},{"id":232,"name":"Dimmer x182","space":1,"level":0},{"id":233,"name":"Dimmer x181","space":1,"level":0},{"id":234,"name":"Dimmer x180","space":1,"level":0},{"id":235,"name":"Dimmer x179","space":1,"level":0},{"id":236,"name":"Dimmer x178","space":1,"level":0},{"id":237,"name":"Dimmer x177","space":1,"level":0},{"id":238,"name":"Dimmer x176","space":1,"level":0},{"id":239,"name":"Dimmer x175","space":1,"level":0},{"id":240,"name":"Dimmer x174","space":1,"level":0},{"id":241,"name":"Dimmer x173","space":1,"level":0},{"id":242,"name":"Dimmer  20","space":1,"level":0},{"id":243,"name":"Dimmer  15","space":1,"level":0},{"id":244,"name":"Dimmer  50","space":1,"level":0},{"id":245,"name":"Dimmer  21","space":1,"level":0},{"id":246,"name":"Dimmer  82","space":1,"level":0},{"id":247,"name":"Dimmer  53","space":1,"level":0},{"id":248,"name":"Dimmer142","space":1,"level":0},{"id":249,"name":"Dimmer146","space":1,"level":0},{"id":250,"name":"Dimmer145","space":1,"level":0},{"id":251,"name":"Dimmer144","space":1,"level":0},{"id":252,"name":"Dimmer143","space":1,"level":0},{"id":253,"name":"Dimmer142","space":1,"level":0},{"id":254,"name":"Dimmer141","space":1,"level":0},{"id":255,"name":"Dimmer140","space":1,"level":0},{"id":256,"name":"Dimmer139","space":1,"level":0},{"id":257,"name":"Dimmer138","space":1,"level":0},{"id":258,"name":"Dimmer137","space":1,"level":0},{"id":259,"name":"Dimmer136","space":1,"level":0},{"id":260,"name":"Dimmer135","space":1,"level":0},{"id":261,"name":"Dimmer134","space":1,"level":0},{"id":262,"name":"Dimmer133","space":1,"level":0},{"id":263,"name":"Dimmer132","space":1,"level":0},{"id":264,"name":"Dimmer131","space":1,"level":0},{"id":265,"name":"Dimmer130","space":1,"level":0},{"id":266,"name":"Dimmer129","space":1,"level":0},{"id":267,"name":"Dimmer128","space":1,"level":0},{"id":268,"name":"Dimmer127","space":1,"level":0},{"id":269,"name":"Dimmer126","space":1,"level":0},{"id":270,"name":"Dimmer125","space":1,"level":0},{"id":271,"name":"Dimmer124","space":1,"level":0},{"id":272,"name":"Dimmer123","space":1,"level":0},{"id":273,"name":"Dimmer122","space":1,"level":0},{"id":274,"name":"Dimmer121","space":1,"level":0},{"id":275,"name":"Dimmer 120","space":1,"level":0},{"id":276,"name":"Dimmer 119","space":1,"level":0},{"id":277,"name":"Dimmer 118","space":1,"level":0},{"id":278,"name":"Dimmer 117","space":1,"level":0}]
5. 

6. 
[{"id":7,"name":"Day","space":2,"state":"Activated"},{"id":8,"name":"Rehearsal","space":2,"state":"Deactivated"},{"id":9,"name":"Show","space":2,"state":"Deactivated"},{"id":10,"name":"Night","space":2,"state":"Deactivated"},{"id":11,"name":"HL-Day","space":1,"state":"Activated"},{"id":12,"name":"HL-Rehearsal","space":1,"state":"Deactivated"},{"id":13,"name":"HL-Show","space":1,"state":"Deactivated"},{"id":14,"name":"HL-Night","space":1,"state":"Deactivated"},{"id":15,"name":"HL-Custom 1","space":1,"state":"Deactivated"},{"id":16,"name":"HL-Off","space":1,"state":"Deactivated"},{"id":17,"name":"Cleaners","space":2,"state":"Deactivated"},{"id":18,"name":"Lecture 1","space":1,"state":"Deactivated"},{"id":19,"name":"Lecture 2","space":1,"state":"Deactivated"},{"id":20,"name":"Lecture 3","space":1,"state":"Deactivated"},{"id":21,"name":"Lecture 4","space":1,"state":"Deactivated"},{"id":22,"name":"Lecture","space":2,"state":"Deactivated"},{"id":23,"name":"Cleaners","space":1,"state":"Deactivated"},{"id":26,"name":"Teaching 1","space":1,"state":"Deactivated"},{"id":27,"name":"Teaching 2","space":1,"state":"Deactivated"}]
7. 
[{"id":0,"name":"Day","state":1},{"id":1,"name":"Rehearsal","state":0},{"id":2,"name":"Show","state":0},{"id":3,"name":"Night","state":0},{"id":4,"name":"WL-SUB STAGE CYCLE","state":0},{"id":5,"name":"Cleaners","state":0},{"id":6,"name":"Lecture","state":0},{"id":10,"name":"Teaching_1","state":0},{"id":11,"name":"Teaching_2","state":0},{"id":12,"name":"Teaching_Off","state":0},{"id":13,"name":"Preset Cleardown","state":0}]

Any blank lines there was no data, there are no sequences or walls in this paradigm file
I'm attaching a screenshot of the channels because it is showing a json error very similar to the companion one
![Screenshot 2024-01-05 at 19 02 53](https://github.com/bitfocus/companion-module-etc-paradigm/assets/13811671/18f000ef-0eeb-4848-a509-c52b284876b8)

**Comment by zerbzman** [comment]
Yep, that looks like the one. It looks like there are some names that have some special characters included. The screenshot is really helpful, thanks. I wonder, in the regular paradigm website interface what the labels for "TRIMMINGS\GALLERY" and "CATWALK\LOBBIES" show. Do you think those are supposed to be slashes or are they supposed to be a space or new line? My guess is that the installer intended them to be slashes but used the wrong slash. It should be a forward slash/ versus a backwards slash\. That backwards slash is messing this up. I can fix it and send you a version to test. Can you shoot me an email to my GitHub username @gmail.com so that I can send you that?

**Comment by retepsmada** [comment]
Sent an email over with a screenshot of what they show up as in the web interface as well.
